[package]
name = "goxlr-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-usb = {path = "../usb" }
goxlr-ipc = {path = "../ipc" }
goxlr-types = {path = "../types" }
simplelog = "0.11.1"
tokio = {version = "1.0", features=["full"]}
log = "0.4.14"
anyhow = "1.0"
strum = { version = "0.23"}
