[package]
name = "goxlr-usb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-types = {path = "../types"}
rusb = "0.9"
thiserror = "1.0"
byteorder = "1"
log = "0.4.14"
enumset = "1.0.8"
